/* Generated By:JavaCC: Do not edit this line. YAL2JVMTreeConstants.java Version 5.0 */
public interface YAL2JVMTreeConstants
{
  public int JJTMODULE = 0;


  public String[] jjtNodeName = {
    "Module",
  };
}
/* JavaCC - OriginalChecksum=d03ff2bde69c669758d77138b1ac4c0a (do not edit this line) */
