/* Generated By:JavaCC: Do not edit this line. YAL2JVMTreeConstants.java Version 5.0 */
public interface YAL2JVMTreeConstants
{
  public int JJTMODULE = 0;
  public int JJTDECLARATION = 1;
  public int JJTVOID = 2;
  public int JJTGLOBALRIGHT = 3;


  public String[] jjtNodeName = {
    "Module",
    "Declaration",
    "void",
    "GlobalRight",
  };
}
/* JavaCC - OriginalChecksum=f367efc84003995864eab68c83088134 (do not edit this line) */
